# #############################::::....
# 導入感謝です！
# 必要な設定はここで行います...
# Material: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Sound   : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Particle: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# ########################::::....

enable: false

# ####################::::....
# 破壊警告の設定です！
ItemDamageNotice:
  # ##############::::....
  # 耐久が減った際に警告するアイテムです。
  # Materialと同じ名前にしてください...
  # Javaのregexが使用できます。
  NoticeItems:
    - "^\\w+sword$"
    - "^\\w+pickaxe$"
    - "^\\w+axe$"
    - "^\\w+shovel$"
    - "^\\w+hoe$"

  # ##############::::....
  # 耐久が指定の割合まで減った際に警告します。
  # 昇順で最初にヒットしたもののみが警告されます。
  # ##### 例 #####::::....
  # # 0~100での警告する割合です。
  # 20:
  #   # 条件に一致した場合の 鳴る音:音量:ピッチ です。
  #   # 鳴る音はSoundと同じ名前にしてください...
  #   # 音量とピッチは小数点でも指定できます！
  #   sound: entity_arrow_hit_player:1:0
  #
  #   # 条件に一致した場合のアクションバーに表示されるテキストです。(必須)
  #   # %item%(アイテムの名前), %max%(最大耐久値), %now%(耐久値) が使用できます。
  #   format: "§7§l(ツール名: %item% / 最大耐久値: %max% / §e§l現在の耐久値: %now%§7§l)"
  Percentages:
    20:
      Sound: "entity_arrow_hit_player:1:0"
      Format: "§7§l(ツール名: %item% / 最大耐久値: %max% / §e§l現在の耐久値: %now%§7§l)"
    5:
      Sound: "entity_arrow_hit_player:1:0"
      Format: "§7§l(ツール名: %item% / 最大耐久値: %max% / §4§l現在の耐久値: %now%§7§l)"

# ####################::::....
# エリトラ補助の設定です！
Elytra:
  # ##############::::....
  # スニークする時間の設定です。
  # 秒数で指定してください。
  # 指定されなかった場合3秒になります。
  Standby: 3

  # ##############::::....
  # エフェクトの設定です。
  # ##### 例 #####::::....
  # # 名前です。(必須)
  # §c§lブレイズ§6のエフェ§eクト:
  #   # 飛行した際 エフェクト:半径:量 です。(必須)
  #   # エフェクトはParticleと同じ名前にしてください...
  #   # 半径は小数点でも指定できます！
  #   Effect: "portal:3:12"
  #   # 設定画面にて表示されるアイテムです。(必須)
  #   # Materialと同じ名前にしてください...
  #   # Javaのregexは使用できません。
  #   Type: ender_pearl
  #   # 設定画面にて表示されるアイテムの説明文です。
  #   Lore:
  #     - "§7紫色の不思議なエフェクト..."
  #   # 設定画面にて表示されるアイテムのカスタムモデルデータです。
  #   CustomModelData: 1
  #   # 設定画面にて表示されるアイテムのダメージ値です。
  #   Damage: 1
  #   # 飛行した際の 鳴る音:音量:ピッチ です。
  #   # 鳴る音はSoundと同じ名前にしてください...
  #   # 音量とピッチは小数点でも指定できます！
  #   sound: "entity_bat_takeoff:1:0"
  Effects:
    §c§lブレイズ§6のエフェ§eクト:
      Effect: "flame:3:12"
      Type: blaze_rod
      Lore:
        - "§7朱色に燃え上がる熱いエフェクト..."
      Sound: "entity_blaze_shoot:1:2"

# ####################::::....
# ランクの設定です。
# ConditionsMiningの数値が多い順から確認されます。
Ranks:
  # ##############::::....
  # ランク名とそのランクになるのに必要な数値を入力してください
  §eTourist: 0
  §2Crafter: 1000
  §2Crafter§5+: 10000
  §dExpert: 30000
  §dExpert§e+: 50000
  §7Miner: 100000
  §7Miner§e+: 200000
  §fSuper§7Miner: 300000
  §fSuper§7Miner§e+: 500000
  §8§lBreaker: 1000000
  §8§lBreaker§d+: 3000000
  §0§lDestroyer: 5000000
  §0§l§ka§0§lDestroyer§0§l§ka: 10000000